version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telegram_bot
    volumes:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: telegram_bot_app
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telegram_bot
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
